CREATE DATABASE Lister;

USE Lister;

CREATE TABLE videogames(
    vg_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    vgName VARCHAR(70),
    vgCompany VARCHAR(70),
    vgYear INT,
    vgGender VARCHAR(70),
    vgCreate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
